[project]
name = "avd"
version = "0.1.1"
description = ""
authors = [
    {name = "davisson.f.deoliveira.mil",email = "davisson.f.deoliveira.mil@army.mil"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pexpect (>=4.9.0,<5.0.0)",
    "playwright (>=1.63.0,<2.0.0)",
    "types-pexpect (>=4.9.0.20260518,<5.0.0.0)"
]

[tool.poetry]
packages = [{include = "avd", from = "src"}]

[project.scripts]
avd = "avd.cli:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
black = "^24.0.0"
pylint = "^3.0.0"
mypy = "^1.8.0"
pytest = "^8.0.0"
pytest-cov = "^4.1.0"

[tool.semantic_release]
version_pattern = 'version = "{version}"'
version_variables = ["pyproject.toml:project.version"]
upload_to_pypi = false